#!/bin/sh
#
# @name HIL Standard VTOL OctoPlane
#
# @type Standard Octo VTOL
# @class VTOL
#
# @maintainer Ildar Sadykov <isadykov@arrival.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
# @output MAIN9 Throttle
# @output MAIN10 Aileron 1
# @output MAIN11 Aileron 2
# @output MAIN12 Elevator
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MAX 25
	param set FW_AIRSPD_MIN 14
	param set FW_AIRSPD_TRIM 16

	param set MC_ROLLRATE_P 0.3

	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_HOR_MAX 2
	param set MPC_THR_MIN 0.1
	param set MPC_TKO_SPEED 1
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15
	param set MPC_Z_VEL_MAX_DN 1.5

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_F_TRANS_DUR 5
	param set VT_F_TRANS_THR 0.75
	param set VT_MC_MOT_COUNT 8
	param set VT_TYPE 2

	param set WEST_EN 1

#	param set VT_FW_MOT_OFFID 12345678
fi

set MAV_TYPE 23

set MIXER standard_vtol_octo_hitl
